---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: %clustername%
  region: %region%
  version: "1.19"

availabilityZones: ["us-east-2a", "us-east-2b", "us-east-2c"]

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-warehouse
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: %namespace%

# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-east-2:699130936416:key/36ddbb63-76bd-4843-b82f-4d1d0cb7368a
